// Originally generated by the Supabase tooling; edited by hand so that the client
// is created lazily instead of at module-evaluation time.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;

/**
 * O Supabase é OPCIONAL neste projeto — o backend padrão é o NestJS.
 * Só o consideramos configurado quando as duas variáveis existem.
 */
export function isSupabaseConfigured(): boolean {
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

let client: SupabaseClient<Database> | null = null;

/**
 * Cria (uma única vez) o cliente Supabase, sob demanda.
 *
 * Antes o `createClient(...)` corria na avaliação do módulo: bastava um import
 * indireto para o app inteiro morrer com "supabaseUrl is required" antes do
 * React montar — ecrã branco. Agora só paga o preço quem realmente usa o
 * Supabase, e com uma mensagem que diz o que fazer.
 *
 * Use `isSupabaseConfigured()` antes de chamar esta função em qualquer caminho
 * que deva continuar a funcionar sem Supabase.
 */
export function getSupabaseClient(): SupabaseClient<Database> {
  if (!isSupabaseConfigured()) {
    throw new Error(
      'Supabase não está configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY ' +
        '(ou VITE_SUPABASE_ANON_KEY) no frontend/.env — ou use os repositórios Nest*, que são o ' +
        'padrão deste projeto.',
    );
  }

  if (!client) {
    client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }

  return client;
}

/**
 * @copyright Copyright (c) 2026 Deullam - Todos os direitos reservados.
 * @license Uso Proprietário. A cópia, distribuição ou modificação deste 
 * ficheiro é estritamente proibida sem autorização prévia.
 */
